### ISSUE TITLE
Program crash

### ISSUE THREAD

**Issue by AlphaCarbon** [augustopereiratx/workers-and-resources-production-calculator#1] opened 2023-10-27 02:46 UTC
When entering the amount of factories you wish to account for, the program crashes. I tested with coal, coal ore, and steel using 1, 2, and 5 factories each. Build was:

soviet-calc_x86_64_windows_v1.0.exe

**Comment by augustotx** [comment] 2023-10-27 02:51
I'm going to fix this ASAP. Did you try to put 1.0, 2.0 etc? Just so I get what the problem is (not on pc right now)

**Comment by AlphaCarbon** [comment] 2023-10-27 03:13
Just tried. Didn't work. I'm running win10 if that matters.

**Comment by augustotx** [comment] 2023-10-27 03:16
aight, I'll check it out soon

**Comment by augustotx** [comment] 2023-10-27 03:29
found the problem. when you run the exe, the script ends and closes. I'll fix it in 5min and upload a new version

**Comment by augustotx** [comment] 2023-10-27 03:36
I think it's fixed now. Please update to v1.0.1 and try it out so I can close the issue

**Comment by AlphaCarbon** [comment] 2023-10-27 04:51
It works!

**Closed as completed** 2023-10-27 04:52 UTC
